spring:
  application:
    name: search-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_search?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:        # 如果没有密码可以不写
      database: 4
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms

# Elasticsearch 配置
elasticsearch:
  host: localhost
  port: 9200
  scheme: http

server:
  port: 15000
