spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/** # 拦截前缀
          filters:
            - StripPrefix=1 # 去掉 /api


        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/** # 拦截前缀
          filters:
            - StripPrefix=1 # 去掉 /api

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/** # 拦截前缀
          filters:
            - StripPrefix=1 # 去掉 /api

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/** # 拦截前缀
          filters:
            - StripPrefix=1 # 去掉 /api


#
#-------------------------------------------------
#

#        - id: bing-route
#          uri: https://cn.bing.com/
#          predicates:
#            - name: Path
#              args:
#                patterns: /search
#            - name: Query
#              args:
#                param: q
#                regexp: haha
##            - Vip=user,leifengyang
#            - name: Vip
#              args:
#                param: user
#                value: leifengyang
#          order: 10
#          metadata:
#            hello: world
#        - id: order-route
#          uri: lb://service-order
#          predicates:
#            - name: Path
#              args:
#                patterns: /api/order/**
#                matchTrailingSlash: true
#          filters:
#            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
#            - OnceToken=X-Response-Token, jwt
#          order: 1
#        - id: product-route
#          uri: lb://service-product
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - RewritePath=/api/product/?(?<segment>.*), /$\{segment}
#          order: 2
#      default-filters:
#        - AddResponseHeader=X-Response-Abc, 123